/// Flutter icons GuruAppIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GuruAppIcons
///      fonts:
///       - asset: fonts/GuruAppIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class GuruIcons {
  GuruIcons._();

  static const _kFontFam = 'GuruAppIcons';

  static const IconData ancillaries_icon = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_right = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData assignment_icon = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData black_cancel = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData black_search = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData black_sort = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData cart_icon = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData category_arts = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData category_sports = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData category_culinary = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData category_science = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData courses_icon = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData edit_icon = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData exclusive_materials_icon = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData facebook_icon = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData google_icon = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData heart_filled = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData home_icon = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData instagram_icon = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData mentors_icon = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData mute_icon = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData password_icon = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData play_button = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData quotes = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData profile_icon = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData sports_courses = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData twitter_icon = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData video_icon = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData youtube_icon = const IconData(0xe81d, fontFamily: _kFontFam);
}
